[tool.poetry]
name = "setrem-developer-testing"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
Flask = "^3.0.2"
requests = "^2.32.3"
boto3 = "1.34.125"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
